# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('isSaltStack', models.BooleanField(default=0, max_length=1)),
                ('status', models.BooleanField(default=0, max_length=1)),
            ],
            options={
                'db_table': 'Host',
            },
        ),
    ]
