# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import utils.customField


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=191, unique=True)),
                ('load', models.TextField()),
            ],
            options={
                'db_table': 'jids',
            },
        ),
        migrations.CreateModel(
            name='saltReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', utils.customField.UnixTimestampField(auto_created=True, null=True)),
                ('fun', models.CharField(max_length=255)),
                ('jid', models.CharField(max_length=191, unique=True)),
                ('minion_id', models.CharField(max_length=255)),
                ('success', models.CharField(max_length=255)),
                ('full_ret', models.TextField()),
                ('returns', models.TextField()),
                ('retcode', models.IntegerField()),
            ],
            options={
                'db_table': 'salt_returns',
            },
        ),
    ]
