# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_jids_saltreturns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
