# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_auto_20171009_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='appTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=50, unique=True)),
                ('startCmd', models.CharField(max_length=255)),
                ('stopCmd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'appTemplate',
            },
        ),
    ]
