# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_apptemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.IntegerField()),
                ('appTempId', models.IntegerField()),
                ('appPath', models.CharField(max_length=255, unique=True)),
                ('appPort', models.IntegerField()),
            ],
            options={
                'db_table': 'hostApplication',
            },
        ),
        migrations.CreateModel(
            name='webApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webTempId', models.IntegerField()),
                ('hostAppId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='webTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'webTemplate',
            },
        ),
    ]
