# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_hostapplication_webapplication_webtemplate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webapplication',
            table='webApplication',
        ),
    ]
