# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20171027_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostapplication',
            name='hostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.host'),
        ),
    ]
