# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0011_auto_20171027_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostapplication',
            name='appTempId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.appTemplate'),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='hostAppId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.hostApplication'),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='webTempId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.webTemplate'),
        ),
    ]
