# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0012_auto_20171027_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apptemplate',
            old_name='appName',
            new_name='appTemplateName',
        ),
        migrations.RenameField(
            model_name='webtemplate',
            old_name='appName',
            new_name='webTemplateName',
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='hostAppName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
