# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0013_auto_20171027_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostapplication',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
