# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0016_auto_20171030_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptemplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webtemplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
