# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0017_auto_20171030_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostapplication',
            name='appTempId',
            field=models.ForeignKey(db_column='appTempId', on_delete=django.db.models.deletion.CASCADE, to='deploy.appTemplate'),
        ),
        migrations.AlterField(
            model_name='hostapplication',
            name='hostId',
            field=models.ForeignKey(db_column='hostId', on_delete=django.db.models.deletion.CASCADE, to='deploy.host'),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='hostAppId',
            field=models.ForeignKey(db_column='hostAppId', on_delete=django.db.models.deletion.CASCADE, to='deploy.hostApplication'),
        ),
        migrations.AlterField(
            model_name='webapplication',
            name='webTempId',
            field=models.ForeignKey(db_column='webTempId', on_delete=django.db.models.deletion.CASCADE, to='deploy.webTemplate'),
        ),
    ]
