# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0019_auto_20171030_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostapplication',
            name='hostId',
            field=models.ForeignKey(db_column='hostId', on_delete=django.db.models.deletion.CASCADE, related_name='appHostId', to='deploy.host'),
        ),
    ]
