# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0020_auto_20171101_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='id',
            new_name='Hid',
        ),
        migrations.AlterField(
            model_name='hostapplication',
            name='hostId',
            field=models.ForeignKey(db_column='hostId', on_delete=django.db.models.deletion.CASCADE, to='deploy.host'),
        ),
    ]
