# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0021_auto_20171101_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='Hid',
            new_name='id',
        ),
    ]
