# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0028_auto_20171102_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostapplication',
            name='appPath',
            field=models.CharField(max_length=255),
        ),
    ]
