# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0029_auto_20171108_1439'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
    ]
