# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import utils.customField


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0030_auto_20171108_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskState',
            fields=[
                ('start_time', utils.customField.UnixTimestampField(auto_created=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jid', models.CharField(max_length=255)),
                ('appId', models.IntegerField()),
                ('end_time', utils.customField.UnixTimestampField(null=True)),
                ('cmd', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='saltreturns',
            name='jid',
            field=models.CharField(max_length=255),
        ),
    ]
