# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0032_auto_20171124_1631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskstate',
            table='taskState',
        ),
    ]
