# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import utils.customField


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0033_auto_20171124_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstate',
            name='appId',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='end_time',
            field=utils.customField.UnixTimestampField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='jid',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
