# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 08:40
from __future__ import unicode_literals

from django.db import migrations
import utils.customField


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0034_auto_20171124_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstate',
            name='end_time',
            field=utils.customField.UnixTimestampField(null=True),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='start_time',
            field=utils.customField.UnixTimestampField(auto_created=True, db_index=True, null=True),
        ),
    ]
