# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0036_auto_20171127_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstate',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
