# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0037_auto_20171127_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstate',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='taskstate',
            name='start_time',
        ),
    ]
