# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0039_auto_20171127_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='appVersionManage',
            fields=[
                ('create_date', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255)),
                ('path', models.TextField(null=True)),
                ('type', models.IntegerField()),
                ('appTemplateName', models.CharField(max_length=255)),
                ('filePackType', models.IntegerField()),
            ],
        ),
    ]
