# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0040_appversionmanage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appversionmanage',
            table='appVersionManage',
        ),
    ]
