# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0041_auto_20171206_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appversionmanage',
            old_name='path',
            new_name='fileName',
        ),
    ]
