# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0042_auto_20171211_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversionmanage',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
