# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0043_auto_20171212_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionmanage',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appversionmanage',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appversionmanage',
            name='version',
            field=models.CharField(default='', max_length=255),
        ),
    ]
