# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0044_auto_20171214_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversionmanage',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
