# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0045_auto_20171219_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionmanage',
            name='filePath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appversionmanage',
            name='fileName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
