# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0047_auto_20171221_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'app_group',
            },
        ),
    ]
