# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0048_app_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionmanage',
            name='appGroupName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appversionmanage',
            name='appTemplateName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
