# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0049_auto_20171222_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_backup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appName', models.CharField(default='', max_length=255)),
                ('fileName', models.CharField(default='', max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
