# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0050_app_backup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='app_backup',
            table='app_backup',
        ),
    ]
