# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0051_auto_20180102_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_backup',
            name='version',
            field=models.CharField(default=255, max_length=255),
        ),
        migrations.AlterField(
            model_name='app_backup',
            name='fileName',
            field=models.TextField(default=''),
        ),
    ]
