# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0052_auto_20180105_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_backup',
            old_name='create_time',
            new_name='create_date',
        ),
    ]
