# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0053_auto_20180105_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_backup',
            name='hostId',
            field=models.ForeignKey(db_column='hostId', default='', on_delete=django.db.models.deletion.CASCADE, to='deploy.host'),
        ),
    ]
