# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0054_app_backup_hostid'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_backup',
            name='backState',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app_backup',
            name='jid',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
