# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0055_auto_20180109_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_backup',
            name='appTemplate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
