# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0056_app_backup_apptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_backup',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
