# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='config_item',
            new_name='config_item1',
        ),
        migrations.AddField(
            model_name='config',
            name='config_item2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
