# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170221_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
