# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170221_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, null=True)),
                ('item', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Item_Config',
            },
        ),
    ]
