# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abnormal_value',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('itemid', models.IntegerField(default=0)),
                ('timestampunix', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=3)),
                ('value', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'abnormal_value',
            },
        ),
    ]
