# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormal_value',
            name='valueType',
            field=models.IntegerField(default=0),
        ),
    ]
