# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_abnormal_value_valuetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormal_value',
            name='hostName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='abnormal_value',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
