# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20180109_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abnormal_value',
            name='ip',
        ),
    ]
