# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_abnormal_value_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormal_value',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
