# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20180209_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormal_value',
            name='itemName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
