# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=600)),
                ('is_up', models.BooleanField(default=0)),
                ('is_show', models.BooleanField(default=0)),
                ('is_config', models.BooleanField(default=0)),
                ('is_admin', models.BooleanField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
