# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_config',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_up',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
